MyComPlatformBundle_homepage:
    pattern:  /
    defaults: { _controller: MyComPlatformBundle:Default:index }

MyComPlatformBundle_list:
    pattern:  /
    defaults: { _controller: MyComPlatformBundle:Default:list }
