parameters:
#    my_com_platform.example.class: MyCom\PlatformBundle\Example

services:
#    my_com_platform.example:
#        class: %my_com_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
